### PR TITLE
Add pt-BR translations

### PR DESCRIPTION
**Pull request by luandro**
Add translations to pt-BR.

### CODE REVIEW

**Comment by arj03** [comment]
Great! You marked this as a draft, I don't see a problem merging this right away unless you want to revise it more? 

I havn't used translation very much, @KyleMaas did all of the work on enabling it. How is the coverage, do we need more strings translated?

**Comment by KyleMaas** [comment]
Excellent!  I'm glad to see someone using this functionality.

**Comment by KyleMaas** [comment]
I love what you've done here, but now I'm going to be greedy and ask: Would you feel comfortable doing a European Portuguese translation as well?  Just so we have a little better coverage of the base "pt" space like how we have a base "en" translation as well as "en-UK".  Even if it's not perfect, you'd have a much better shot at getting it close than either @arj03 or I.

Heck, for that matter, you'd probably have a better shot at the other Romance languages than either of us.  If you want to try and tackle one of those, that'd be awesome.  Again, even if you just get close, it's better than we'd be able to do.  The Japanese translation is mostly machine-translated with corrections based on my very limited knowledge of Japanese (my proficiency in everyday Japanese is not great, but my technical Japanese proficiency is nearly non-existent without help, hence the machine translation base).

**Comment by KyleMaas** [comment]
If not, I still have no problems merging this.  I just figured I'd be greedy and ask.  :)

**Comment by luandro** [comment]
@KyleMaas I have no idea what's the difference between Brazilian and European Portuguese. We can just copy this and use it as `pt` until someone from Portugal may want to correct it. I can also help translating to Spanish. I built this [json-translator](https://github.com/luandro/json-translator) for machine translation.

I'm still waiting for some peers to review to remove draft status.

**Comment by KyleMaas** [comment]
@luandro Sounds good.  Translator utility looks quite handy.  Thanks!

**Review by henrique2Zs — COMMENTED** [review]
Guys, I'm new here, and I'm not sure if I could do this review. If wanted more review tell me that I can continue. Bye!

**Comment by luandro** [comment]
@henrique2Zs thank you very much! Please continue as you like.

**Comment by luandro** [comment]
Should be good to go!

**Comment by arj03** [comment]
Sweet, thanks! :heart:

**Pull request merged**
