### PR TITLE
Add mnemonic key recovery to onboarding

### LINKED ISSUE #255: Load mnemonic key from onboarding screen
Probably would be a good option to allow for onboarding to take in a mnemonic key to restore an account rather than having users set up a new profile and then go to the profile page to load in a key.  I've done it a bunch of times, but thinking about it, it's a non-obvious UI flow.

Implementation-wise, it's not the easiest thing to do, since IIRC the new key is actually generated before the onboarding screen is shown.  So we'd need to generate a new key, show the onboarding screen, replace the key, then reload the page.

Not difficult.  Wouldn't be a bad first project for somebody.

### PR DESCRIPTION
**Pull request by KyleMaas**
Allow the user to choose to onboard as a new user or go straight to loading from a mnemonic key.

Fixes #255

### CODE REVIEW

**Comment by KyleMaas** [comment]
I'll note that I filed this bug due to a quirk I had to work around to get this to work:

https://github.com/egoist/vue-slim-tabs/issues/141

**Comment by KyleMaas** [comment]
It works properly now.  But it did take some trial and error to work around that bug.  At least the bug was consistent so I could.  :)

**Comment by arj03** [comment]
This is great, can't count how many times I have needed something like this :) I'll let this simmer a day or two and see if upstream responds to your issue.

**Comment by KyleMaas** [comment]
Thanks!  I already worked around that issue, so it shouldn't affect this.  It was just a long road finding what exactly triggered it.  In this case, it happened if I put anything after the `<textarea>` on the second tab.  If I did, then you could switch to that tab but couldn't switch back.  So I just moved the WARNING and NOTE messages outside of the tab area, and now everything's hunky dory.  But it is a bug to be aware of if you ever try to add anything to that tab.

(I did look at other tab libraries.  But this one seemed to be about the simplest, most stable, and smallest I could find.  So working around the bug seemed to be worth it.)

**Comment by arj03** [comment]
Great work! I just tested this and work perfectly.

**Comment by KyleMaas** [comment]
Awesome.  Thanks!

**Pull request merged**
