### PR TITLE
Fixing other Unicode characters which wouldn't display for me

### PR DESCRIPTION
**Pull request by KyleMaas**
Changes Unicode characters for new messages to the envelope character.

### CODE REVIEW

**Comment by arj03** [comment]
Is this because the noto font is not loading for you?

**Comment by KyleMaas** [comment]
Yes.  noto-emoji is a separate package on Gentoo.  I installed it, and now I get the party bugle emoji.  But is that something that's a good thing to count on?  If you'd rather stick with that emoji, maybe it'd be a good idea to embed the Noto emoji font?

**Comment by KyleMaas** [comment]
I guess for that matter, the emoji font is also used for post reactions, so maybe it'd be a good idea to embed the font anyway.

**Comment by arj03** [comment]
It should be included? https://github.com/arj03/ssb-browser-demo/blob/master/css/NotoColorEmoji.ttf

**Comment by KyleMaas** [comment]
Hm.  Well, looks like I've got a bug to fix, then.  Uninstalled system-wide noto-emoji, and I'll see if I can hunt it down.

**Comment by KyleMaas** [comment]
Figured it out.  When installed as a system font, Noto Color Emoji was being pulled in as a fallback.  But the embedded version only worked for things in the "emoji" CSS class.  This latest commit adds NotoColorEmoji (the locally-embedded name) as a fallback font for the entire page, which fixes the problems with emojis for me.

**Comment by arj03** [comment]
The css fix looks good. To be honest I liked the notification icons better before, the envelope is very to see on that background.

**Comment by KyleMaas** [comment]
That should revert that change, leaving only the CSS change.  It does seem to work now with the font uninstalled from the system so it can only use the embedded version.

**Comment by arj03** [comment]
Perfect, thanks :)

**Pull request merged**
