### PR TITLE
Add translations

### PR DESCRIPTION
**Pull request by KyleMaas**
* Fix a couple typos in the base English translation.
* Add Japanese translation based mostly on machine translation with some minor tweaks from my not-even-N5 level of Japanese proficiency.
* Add Pirate translation, per https://github.com/arj03/ssb-browser-demo/issues/103#issuecomment-766156259

### CODE REVIEW

**Comment by KyleMaas** [comment]
I will note that I'm sure the Japanese will need to be corrected.  It's a start.  I have a passing familiarity with really basic Japanese, but it's nowhere near that of a native speaker, and the technical level of a lot of our strings is way above my skill level.  So I'm hoping the machine translation did a reasonable job, although I did correct some of what looked like really bad translations.

**Comment by arj03** [comment]
Great thanks

**Comment by arj03** [comment]
Lol this pirate translation is golden. It seems like there are quite a few things that still needs translating?

**Comment by KyleMaas** [comment]
By all means, please add more!  I was running out of ideas.

**Pull request merged**
