### PR TITLE
Add support for DHT connections to the Connections screen

### PR DESCRIPTION
**Pull request by KyleMaas**
This adds support for accepting DHT invites via the Connections screen.  Must be used in conjunction with the changes in ssb-browser-core in the pull request at:

https://github.com/arj03/ssb-browser-core/pull/11

I will note that at this time, it does not seem to actually connect.  I'm unsure what the reason is.  But as far as I can tell, ssb-browser-core is able to accept the connection as working, so I have to assume the problem is in the scheduling.  I could use some help with this aspect of this.

### CODE REVIEW

**Comment by arj03** [comment]
Overall I think this looks good. I looked at the browser core changes and they seem fine. It would be easier to test if there was a create invite button that called start & create so that one could test this directly between two browsers. Can you add that @KyleMaas?

**Comment by KyleMaas** [comment]
I can try.

**Comment by KyleMaas** [comment]
That adds the button and invite code screen.  It still doesn't actually connect, and I don't understand why, but the functionality on the UI side appears to be working.

**Comment by KyleMaas** [comment]
I think I've figured out why accepting doesn't work.  multiserver-dht uses discovery-swarm, which internally tries to call net.createServer(), which supposedly has iffy support on the browser client side.  It looks like it might be good to try to port multiserver-dht to hyperswarm instead.  See this issue:

https://github.com/staltz/multiserver-dht/issues/3

**Comment by KyleMaas** [comment]
See #22.  I got this to work and was able to successfully test it.

**Comment by arj03** [comment]
Amazing! This is really exciting. Will wait with looking at this until upstream PRs are applied. Will look at the about & suggest very soon.

**Comment by KyleMaas** [comment]
@arj03 We now have pull request #125 which works without manual dependency patching, if you want to try this out.

**Comment by KyleMaas** [comment]
@staltz merged the changes to multiserver-dht.  So now, I think we're down to just needing this:

https://gitlab.com/staltz/ssb-dht-invite/-/issues/2

Once that's in place, I should be able to push a version of this that works without depending in my own patched forks of things.

**Comment by KyleMaas** [comment]
This has stagnated long enough I think I'm going to just close this.

**Pull request closed without merging**
