### PR TITLE
Update ToastUI-Vue editor 3.0.0

### LINKED ISSUE #298: Update vue editor
Hey @KyleMaas 

I noticed that the Vue editor has a new major release that is quite a bit smaller. I was wondering if that would be something you would be up for upgrading?

### PR DESCRIPTION
**Pull request by KyleMaas**
This partially works.  Problems so far include:

* ~Clicking a suggestion in a popup suggestion box (like for channels or people) does not work on the first try.  Subsequent suggestion clicks do seem to work.~
* ~Adding images does not work properly.~

Fixes #298

### CODE REVIEW

**Comment by arj03** [comment]
Great first pass there. I tried checking out this branch and building, it's 150kb smaller. And that is not including the css file one doesn't need to include.

**Comment by KyleMaas** [comment]
That pretty much works.  Found an interesting bug I need to file, but it's unrelated to this.  Think I'm going to take this out of Draft status now.  Make sure you test this well before merging, though - the underlying editor is considerably different, so I'm not confident I've handled all edge cases.

**Comment by KyleMaas** [comment]
Inlined size before: 7,831,765 bytes

Inlined size after: 12,193,483 bytes

Something weird going on...

**Comment by KyleMaas** [comment]
Not sure what's going on with inlining.  I'm not seeing much (if any) difference between release build sizes between the master branch and this one.  So if you're good with how this works, go for it, and I'll try and troubleshoot inlining later.

**Comment by arj03** [comment]
Btw one of the audit errors is from the inline tool.

**Comment by arj03** [comment]
I'm testing this now, seems to be working, will fix #300 before merging.

**Comment by arj03** [comment]
This looks really good. Thanks for taken on this. The js reduction is quite substantial. The css is a bit bigger, but not anything close to the increase you are seeing in the inline tool.

**Comment by KyleMaas** [comment]
For whatever reason, this merge is messing up pulling master.

**Comment by arj03** [comment]
What, that's strange. Works fine here. Sure you are on master? :)

**Comment by KyleMaas** [comment]
Yep.  Don't know what's going on, but something's goofed up badly.  Wiping and re-cloning to see if that works.

**Comment by KyleMaas** [comment]
Not sure what happened but wiping and reloading seems to have fixed it.

**Pull request merged**
