### PR TITLE
Use ssb-friends

### PR DESCRIPTION
**Pull request by arj03**
Depends on [PR](https://github.com/arj03/ssb-browser-core/pull/22)

### CODE REVIEW

**Comment by KyleMaas** [comment]
Oh, nice.  I guess I didn't realize before looking at this, but this allows for hops != 1, doesn't it?

**Comment by arj03** [comment]
It does, its just not 100% hooked up yet.

**Comment by KyleMaas** [comment]
Awesome.  Looking forward to it.

**Comment by KyleMaas** [comment]
Looking over this, I can see one thing we'll have to watch out for.  With the contacts index gone, we will need a different method of figuring out blocking status, since I believe that's based on that index everywhere that we check it.

**Comment by arj03** [comment]
Yes, there should be a similar method on ssb-friends. I'll see if I can get them all in the PR.

**Comment by arj03** [comment]
This needs a good round of testing. I'm going to experiment a bit with the old about index.

**Comment by arj03** [comment]
Decided to do the about thing as well. There is something strange with level in the browser, it's like 40x slower. But it should be ok if we just stream the profiles instead of waiting for all.

**Comment by KyleMaas** [comment]
Really excited about this!

Don't forget to merge in changes from the master branch when you do your testing - the blocked-profiles feature does have a new blocking check in it that will need to be ported to this.

**Comment by arj03** [comment]
I already did :) We need to hammer out the bugs in this and then I think we can release 4.2.0

**Comment by KyleMaas** [comment]
Cool.  Let me know when it's ready for testing.

**Comment by arj03** [comment]
@KyleMaas it should be ready now. 

I found one bug that I think it unrelated to this PR when on a /profile page:

```
TypeError: Cannot read property 'mdEditor' of null
    at a.hideSuggestions (bundle-ui.js:165016)
    at He (vue.min.js:6)
    at a.n (vue.min.js:6)
    at He (vue.min.js:6)
    at a.e.$emit (vue.min.js:6)
    at a.forEach.e.<computed> (bundle-ui.js:18235)
    at bundle-ui.js:12991
    at forEachOwnProperties (bundle-ui.js:12306)
    at EventManager.emit (bundle-ui.js:12991)
    at MarkdownEditor._setToolbarState (bundle-ui.js:14658)
```

I feel like this is pretty good now. There are probably some more bugs, but at least this feels good. Also the API got a bit nicer. And +269 −323 is always a good sign :)

**Comment by KyleMaas** [comment]
I noticed that one last night when I was working on something else.  It happened when it tried to hide a suggestions popup after having navigated to a different page when the Markdown editor was already torn down.  Should be easy enough to fix.

**Comment by arj03** [comment]
It's still marked as draft until we merge the ssb-friends.

**Comment by arj03** [comment]
@KyleMaas word of warning, if you update to jitdb 2.0.4 then most things will not work until you clear the indexes. Furthermore this is a [bug](https://github.com/ssb-ngi-pointer/jitdb/issues/114). We'll fix that tomorrow. So my recommendation if you want to look at some of the groups things is probably to stay on master and just make your changes there.

**Comment by KyleMaas** [comment]
I ended up just cherry picking your CSS tweak commit into the User Groups Improvements branch.  Hopefully that way we won't have merge conflicts.

**Comment by KyleMaas** [comment]
So with the jitdb bump, is this ready to test?

**Comment by arj03** [comment]
It is :)

**Comment by KyleMaas** [comment]
This is *way* faster.  UI is just overall much less laggy.  And so far, the only glitch I'm seeing is that if I look at a page with a blocked profile, I get a 404 error in the log:

GET http://127.0.0.1:8080/undefined 404 (Not Found)

So for some reason, it's coming back as 'undefined' instead of 'assets/noavatar.svg' or the actual avatar of the person.

**Comment by KyleMaas** [comment]
Huh.  The actual element shows noavatar in the src.  So I'm not sure what's trying to pull `http://127.0.0.1:8080/undefined`.  But it seems to consistently happen on the profile page (at least) when it shows a blocked profile.

**Comment by KyleMaas** [comment]
Ah, I think I found it.  It happens when you look at your own profile if you have an image in your description.  I think it's that the editor is trying to preview it before it's had a chance to load the image's URL into the cache.  So that's probably unrelated to this pull request.

**Comment by KyleMaas** [comment]
This looks pretty good.  I've been clicking around like a madman trying to explore enough to get things to break, and so far it's just working (with the exception of that 404 that doesn't seem to be from this).

**Comment by arj03** [comment]
Cool. Thanks for testing. I'll be doing a release soon :)

**Comment by KyleMaas** [comment]
Yay!

**Pull request merged**
