### PR TITLE
Mobile Tweaks 2, Electric Boogaloo

### PR DESCRIPTION
**Pull request by KyleMaas**
This fixes the profile link at the bottom.  Turns out it was due to this:

[Prop Casing (camelCase vs kebab-case)](https://vuejs.org/v2/guide/components-props.html#Prop-Casing-camelCase-vs-kebab-case)

It also makes it so that it updates when you save your profile.

Still can't find a way to duplicate the Profile editor not working, though.

### CODE REVIEW

**Comment by KyleMaas** [comment]
Latest CSS tweaks fix the problems with these under a simulator:

* LG Optimus L70 (384x640)
* Nokia Lumia 520 (320x533)
* JioPhone 2 (240x320)

**Comment by KyleMaas** [comment]
I also changed it so that if the screen width is too small for the lower nav menu to actually be usable, it switches back to traditional upper navigation.  It may take up more space, but it actually works, as opposed to when the lower nav menu is too wide and clips to the screen because it can't wrap.

**Comment by arj03** [comment]
Tested this. The profile editor seems to be working now. Great fix on the profile link :)

**Comment by KyleMaas** [comment]
Perfect.  Hard to debug that without being able to duplicate it.  Glad it worked.

**Pull request merged**
