### PR TITLE
Show loading message

### LINKED ISSUE #292: Thread view is broken
Clicking on a thread link shows the thread as a single message - "undefined".  Happens with every thread I've tried.  Clicking RAW results in:

```
{
  "key": "",
  "value": {
    "content": {}
  }
}
```

### PR DESCRIPTION
**Pull request by KyleMaas**
Show a loading message when waiting for results from a message search on the Thread and Threads pages.

Fixes #292

### CODE REVIEW

**Comment by arj03** [comment]
This looks good. Let me test it before merging. Btw great to see you back :)

I'm currently testing a greater refactor of connection and replication handling https://github.com/arj03/ssb-browser-core/pull/52. I'll post a PR to ssb-browser-demo a bit later today. Are you up for helping to testing that? :)

**Comment by KyleMaas** [comment]
Good to be back.  Like I said a few months ago, my free time tends to come and go.  So I try to pack as much into my free time as I can.

Sure, I'd be up for helping with testing.  I've been watching the comments on the refactors and it looks like a lot's been going on, but I haven't kept up with what exactly you've been working on.  And "Undermuda" doesn't help much with explaining what the goals are.  What all needs to be tested, and is it ready to test now or are you still working on it?

**Comment by arj03** [comment]
Unbermuda refers to the holy trinity of ssb-replicate, ssb-friends and ssb-ebt. Before they were all tied together, one calling another, sometimes overwriting methods etc. It was a total mess. So we jokingly referred to this as the bermuda triangle, the place people go and never come back. Staltz did a great job of untangling all of this so that friends and ebt only does 1 thing. Replicate is not used anymore. Instead things are orchestrated through a small [module](https://github.com/arj03/ssb-replication-scheduler). I had to change this a bit to work in browser-core for partial replication. This is step 1 of enabling proper partial replication.

This branch should allow you to test: https://github.com/arj03/ssb-browser-demo/pull/297

**Comment by arj03** [comment]
Thanks, this seems to be working :)

**Pull request merged**
