### PR TITLE
Offline mode

### LINKED ISSUE #153: Offline mode
> I would actually rather have an offline mode.

From @arj03 here: https://github.com/arj03/ssb-browser-demo/issues/140#issuecomment-771134863

### PR DESCRIPTION
**Pull request by KyleMaas**
Adds an "offline mode" in Connections, along with connectivity status information.  Builds off of and extends #154.

Uses functionality from https://github.com/arj03/ssb-browser-core/pull/20 if available, but it does work without it.

Fixes #153.

### CODE REVIEW

**Comment by KyleMaas** [comment]
Fixed merge conflicts.

**Comment by arj03** [comment]
From a quick review, this looks good. Will merge soon :)

**Comment by arj03** [comment]
nice touch with the [x] :)

**Comment by KyleMaas** [comment]
Thanks!  I figured that would make it a little clearer what it's doing.

**Pull request merged**
