### PR TITLE
Add support for internationalization

### PR DESCRIPTION
**Pull request by KyleMaas**
* Adds support for internationalization based on the browser's locale, if available.
* Moves strings to an internationalization dictionary in messages.json.
* Adds a UK English translation.
* Adds a setting to override the browser's locale under Settings.

### CODE REVIEW

**Comment by arj03** [comment]
Ok I guess. Is messages.json missing from this PR? Looks like it needs to be included?

**Comment by KyleMaas** [comment]
Huh.  You're right.  Should have it now.

**Comment by arj03** [comment]
@KyleMaas is there a way to make [vue-i18n] less noisy by default? I get a ton of warnings in my console with this enabled :)

**Comment by KyleMaas** [comment]
I can try.  What is your browser's default locale set to (navigator.language)?

**Comment by arj03** [comment]
Its set to "en-GB"

**Pull request merged**
