### PR TITLE
Add setting to enable detailed logging (EBT logging for now)

### PR DESCRIPTION
**Pull request by KyleMaas**
Add a setting to enable advanced detailed logging.  See:

https://github.com/arj03/ssb-browser-demo/issues/140#issuecomment-790889512

### CODE REVIEW

**Comment by arj03** [comment]
Will have a look at this soon. 

On a related note I just fixed a bug in EBT that was merged today. I updated between-two-worlds with the fix which means that I get data from a few more feeds than before.

**Comment by KyleMaas** [comment]
This look okay?

**Comment by arj03** [comment]
Yeah thx

**Comment by KyleMaas** [comment]
Thanks!

**Pull request merged**
