### PR TITLE
Channel index

### PR DESCRIPTION
**Pull request by KyleMaas**
Use the new channel index.  Draft for now until we figure out if this is a good way to do this.

### CODE REVIEW

**Comment by KyleMaas** [comment]
Fixes #189.

**Comment by KyleMaas** [comment]
Couple merge conflicts, but those will have to be updated anyway to whatever the new version of ssb-browser-core is.

**Comment by arj03** [comment]
This looks great from reading the code

**Comment by arj03** [comment]
core 8.1.0 ready :)

**Comment by KyleMaas** [comment]
Merge conflicts fixed.

**Pull request merged**
