### PR TITLE
If ssb-meme is installed, use it to suggest memes

### LINKED ISSUE #124: Search blob feature
Patchbay had this super awesome feature where if you are in a input field, you could type % (I think it was) an popup would allow you to search for blobs and include in the text. This gave a really nice universe where people would tag their blobs and in this way a whole universe of expressions opened up that was potentially much more rich than just text. Not to say more fun :)

@KyleMass this was the feature I was referring to. Not sure how easy or hard it is to implement. But there is some code in patchbay somewhere to do this.

### PR DESCRIPTION
**Pull request by KyleMaas**
If ssb-meme (a version compatible with db2) is installed, use it to suggest memes in Markdown editors when the user types "&".

Fixes #124, assuming ssb-meme is installed.

### CODE REVIEW

**Comment by arj03** [comment]
Thanks. Also putting this on the back burner until after the weekend :-)

**Comment by KyleMaas** [comment]
No problem.  I figured that'd be the case.

**Comment by KyleMaas** [comment]
I should probably put this here - this needs:

https://github.com/ssbc/ssb-meme/issues/6

**Comment by KyleMaas** [comment]
Going to convert this to a draft until ssb-meme is updated.

**Comment by KyleMaas** [comment]
This has stagnated long enough I think I'm going to just close this.

**Pull request closed without merging**
