### PR TITLE
Remove autorefresh feature

### PR DESCRIPTION
**Pull request by arj03**
This removed the feature as argued [here](https://github.com/arj03/ssb-browser-demo/pull/115#issuecomment-766419729)

### CODE REVIEW

**Comment by KyleMaas** [comment]
Is it possible you could just set the default preference to disabled instead (defaultprefs.json as of pull request #115)?  That way, I can continue to work on this.

**Comment by arj03** [comment]
I could, it needs to be applied a few more places then. Just trying to feel how much you really like this feature? ;)

**Comment by KyleMaas** [comment]
I actually use it quite a bit.  It's nice for being able to passively watch Public while working on something else.

**Comment by arj03** [comment]
Alright, will do that instead then :)

**Comment by KyleMaas** [comment]
Thanks!

**Comment by arj03** [comment]
I pushed up the disable now

**Comment by KyleMaas** [comment]
Cool.  That should work.

**Pull request closed without merging**
